name: Lint Code
on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install/update pip and reqirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements
      - name: Run isort
        run: isort --check demo_ui.py
      - name: Run pylint
        run: pipenv run pylint demo_ui.py --fail-under 9.5
      - name: Run flake8
        run: pipenv run flake8 --max-line-length 120
